# Generated by Django 4.0.4 on 2022-04-20 15:48

import common.models.profile
import common.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='4文字以上15文字以下にする必要があります。半角英数字とアンダースコア（_）のみです。スペースを含めることはできません。アンダースコア（_）から始めることはできません。', max_length=15, unique=True, validators=[common.models.user.UsernameValidator()], verbose_name='ユーザー名')),
                ('account_name', models.CharField(help_text='10文字以下にする必要があります。', max_length=10, validators=[common.models.user.AccountnameValidator()], verbose_name='アカウント名')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'ordering': ['username'],
                'abstract': False,
            },
            managers=[
                ('objects', common.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='image/common/user_icon/hiyokko.png', upload_to='image/common/user_icon/', verbose_name='アイコン')),
                ('bio', models.CharField(blank=True, help_text='最大140文字です。', max_length=140, verbose_name='自己紹介')),
                ('classic_level', models.ForeignKey(default=common.models.profile.get_or_create_default_level, on_delete=django.db.models.deletion.PROTECT, related_name='users', related_query_name='user', to='classic.level', verbose_name='レベル')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール',
            },
        ),
    ]
