# Generated by Django 4.0.4 on 2022-05-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['classic_level'], 'verbose_name': 'プロフィール', 'verbose_name_plural': 'プロフィール'},
        ),
    ]
