# Generated by Django 4.0.4 on 2022-04-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncheck',
            name='checker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_checks', related_query_name='question_check', to=settings.AUTH_USER_MODEL, verbose_name='校閲者'),
        ),
        migrations.AddField(
            model_name='questioncheck',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_checks', related_query_name='question_check', to='classic.question', verbose_name='お題'),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', related_query_name='created_question', to=settings.AUTH_USER_MODEL, verbose_name='出題者'),
        ),
        migrations.AddField(
            model_name='match',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic.contest', verbose_name='コンテスト'),
        ),
        migrations.AddField(
            model_name='match',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic.level', verbose_name='レベル'),
        ),
        migrations.AddField(
            model_name='match',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classic.question', verbose_name='お題'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', related_query_name='favorite', to='classic.answer', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', related_query_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='answerreview',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_reviews', related_query_name='answer_review', to='classic.answer', verbose_name='投票回答'),
        ),
        migrations.AddField(
            model_name='answerreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_reviews', related_query_name='answer_review', to=settings.AUTH_USER_MODEL, verbose_name='投票者'),
        ),
        migrations.AddField(
            model_name='answer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='classic.match', verbose_name='マッチ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='panellist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', related_query_name='answer', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
    ]
