# Generated by Django 4.0.4 on 2022-04-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', related_query_name='match', to='classic.contest', verbose_name='コンテスト'),
        ),
        migrations.AlterField(
            model_name='match',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', related_query_name='match', to='classic.level', verbose_name='レベル'),
        ),
    ]
