# Generated by Django 4.0.4 on 2022-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0003_alter_match_contest_alter_match_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_held',
            field=models.BooleanField(default=False, verbose_name='開催中'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_held', True)), fields=('is_held',), name='unique_is_held'),
        ),
    ]
