# Generated by Django 4.0.4 on 2022-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0008_questioncheck_unique_question_check'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('contest', 'level'), name='unique_contest_level'),
        ),
    ]
