# Generated by Django 4.0.4 on 2022-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0009_match_unique_contest_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='unique_favorite_answer_user'),
        ),
    ]
