# Generated by Django 4.0.4 on 2022-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0010_favorite_unique_favorite_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='カラー'),
        ),
    ]
