# Generated by Django 4.0.4 on 2022-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0011_level_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.IntegerField(null=True, verbose_name='オーダー'),
        ),
    ]
