# Generated by Django 4.0.4 on 2022-05-06 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classic', '0013_alter_level_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order'], 'verbose_name': 'レベル', 'verbose_name_plural': 'レベル'},
        ),
        migrations.AlterField(
            model_name='answerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_reviews', related_query_name='answer_review', to=settings.AUTH_USER_MODEL, verbose_name='投票者'),
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=20, verbose_name='コメント')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント時刻')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', related_query_name='answer_comment', to='classic.answer', verbose_name='コメント回答')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', related_query_name='answer_comment', to=settings.AUTH_USER_MODEL, verbose_name='コメンテーター')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['-id'],
            },
        ),
    ]
