# Generated by Django 4.0.4 on 2022-05-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0014_alter_level_options_alter_answerreview_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerreview',
            name='comment',
        ),
    ]
