# Generated by Django 4.0.4 on 2022-05-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='回答')),
                ('rank', models.IntegerField(default=0, verbose_name='順位')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('date_answered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回答時刻')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='レベル')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='カラー')),
                ('order', models.IntegerField(unique=True, verbose_name='オーダー')),
            ],
            options={
                'verbose_name': 'レベル',
                'verbose_name_plural': 'レベル',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/scramble/question_image/', verbose_name='お題画像')),
                ('text', models.CharField(max_length=60, verbose_name='お題')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成時刻')),
                ('was_checked', models.BooleanField(default=False, verbose_name='校閲済み')),
                ('is_safe', models.BooleanField(default=False, verbose_name='出題可能')),
                ('was_asked', models.BooleanField(default=False, verbose_name='出題済み')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scr_questions', related_query_name='created_scr_question', to=settings.AUTH_USER_MODEL, verbose_name='出題者')),
            ],
            options={
                'verbose_name': 'お題',
                'verbose_name_plural': 'お題',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', related_query_name='match', to='scramble.level', verbose_name='レベル')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scramble.question', verbose_name='お題')),
            ],
            options={
                'verbose_name': 'マッチ',
                'verbose_name_plural': 'マッチ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録時刻')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', related_query_name='favorite', to='scramble.answer', verbose_name='回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scr_favorites', related_query_name='scr_favorite', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, choices=[(0, '0点'), (2, '2点'), (3, '3点'), (4, '4点')], default=0, verbose_name='点数')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_reviews', related_query_name='answer_review', to='scramble.answer', verbose_name='投票回答')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scr_answer_reviews', related_query_name='scr_answer_review', to=settings.AUTH_USER_MODEL, verbose_name='投票者')),
            ],
            options={
                'verbose_name': '採点詳細',
                'verbose_name_plural': '採点詳細',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=20, verbose_name='コメント')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント時刻')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', related_query_name='answer_comment', to='scramble.answer', verbose_name='コメント回答')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scr_answer_comments', related_query_name='scr_answer_comment', to=settings.AUTH_USER_MODEL, verbose_name='コメンテーター')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='scramble.match', verbose_name='マッチ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='panellist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scr_answers', related_query_name='scr_answer', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='unique_scr_favorite_answer_user'),
        ),
        migrations.AddConstraint(
            model_name='answerreview',
            constraint=models.UniqueConstraint(fields=('answer', 'reviewer'), name='unique_scr_answer_review'),
        ),
    ]
