# Generated by Django 4.0.4 on 2022-05-19 05:10

from django.db import migrations, models
import django.utils.timezone
import scramble.models.match


class Migration(migrations.Migration):

    dependencies = [
        ('scramble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date_asked',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='出題時刻'),
        ),
        migrations.AddField(
            model_name='match',
            name='date_marked',
            field=models.DateTimeField(default=scramble.models.match.after_ten_minutes, verbose_name='採点終了時刻'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_asked',
            field=models.BooleanField(default=False, verbose_name='出題中'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_held',
            field=models.BooleanField(default=False, verbose_name='開催中'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_marked',
            field=models.BooleanField(default=False, verbose_name='採点中'),
        ),
        migrations.AddField(
            model_name='match',
            name='post_deadline',
            field=models.DateTimeField(default=scramble.models.match.after_ten_minutes, verbose_name='回答締切時刻'),
        ),
        migrations.AddField(
            model_name='match',
            name='was_marked',
            field=models.BooleanField(default=False, verbose_name='採点済み'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('is_held', True)), fields=('is_held',), name='unique_scr_is_held'),
        ),
    ]
